//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TSTEntities : DbContext
    {
        public TSTEntities()
            : base("name=TSTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tstDepartment> tstDepartments { get; set; }
        public virtual DbSet<tstEmployee> tstEmployees { get; set; }
        public virtual DbSet<tstEmployeeStatu> tstEmployeeStatus { get; set; }
        public virtual DbSet<tstTechNote> tstTechNotes { get; set; }
        public virtual DbSet<tstTicketPriorty> tstTicketPriorties { get; set; }
        public virtual DbSet<tstTicket> tstTickets { get; set; }
        public virtual DbSet<tstTicketStatu> tstTicketStatus { get; set; }
    }
}
