//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tstEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tstEmployee()
        {
            this.tstTechNotes = new HashSet<tstTechNote>();
            this.tstTickets = new HashSet<tstTicket>();
            this.tstTickets1 = new HashSet<tstTicket>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Lname { get; set; }
        public System.DateTime Hiredate { get; set; }
        public string UserID { get; set; }
        public int StatusID { get; set; }
        public string Jobtitle { get; set; }
        public string Adress { get; set; }
        public string Adress2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public int DepID { get; set; }
        public string ImmageURL { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> Dateofbirth { get; set; }
        public Nullable<System.DateTime> separationDate { get; set; }
    
        public virtual tstDepartment tstDepartment { get; set; }
        public virtual tstEmployeeStatu tstEmployeeStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tstTechNote> tstTechNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tstTicket> tstTickets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tstTicket> tstTickets1 { get; set; }
    }
}
