//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tstTicket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tstTicket()
        {
            this.tstTechNotes = new HashSet<tstTechNote>();
        }
    
        public int ID { get; set; }
        public int SubmitbyID { get; set; }
        public Nullable<int> TechID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ResoloutionDate { get; set; }
        public string TroubleDescription { get; set; }
        public string Screenshot { get; set; }
        public int StatusID { get; set; }
        public int PriorityID { get; set; }
        public string Subject { get; set; }
    
        public virtual tstEmployee tstEmployee { get; set; }
        public virtual tstEmployee tstEmployee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tstTechNote> tstTechNotes { get; set; }
        public virtual tstTicketPriorty tstTicketPriorty { get; set; }
        public virtual tstTicketStatu tstTicketStatu { get; set; }
    }
}
